buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
        //maven { url "https://maven.cleanroommc.com" }
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.53', changing: true
    }
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'eclipse'


version = mod_version
group = project.findProperty('group') ?: 'astrotweaks'
archivesBaseName = '[1.12.2] AstroTweaks'

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

minecraft {
    mappings channel: 'snapshot', version: '20171003-1.12'

    //accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                astrotweaks {
                    source sourceSets.main
                }
            }
        }
        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                astrotweaks {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    mavenCentral()
    maven { url 'https://maven.blamejared.com/' }
    maven { url 'https://oss.sonatype.org/content/groups/public/' }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2860'

    compileOnly "mezz.jei:jei_1.12.2:4.16.1.302"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}
//tasks.withType(Jar).configureEach {
	//archiveBaseName.set(archivesBaseName)
	//archiveVersion.set(version)

    // deletes timestamps of files inside the archive
    //preserveFileTimestamps = false
//}

jar {
    manifest {
        attributes(
            //'FMLCorePlugin': 'astrotweaks.CoreModLoader',
            //'FMLCorePluginContainsFMLMod': 'true',
            'ForceLoadAsMod': 'true',
            'TweakOrder': '0',
            //'Maven-Artifact': "${project.group}:${project.archivesBaseName}:${project.version}",
            //'Timestamp': System.currentTimeMillis(),
            'Specification-Title': 'AstroTweaks',
            'Specification-Vendor': 'AstroTweaks',
            'Specification-Version': '1',
            'Implementation-Title': project.name,
            'Implementation-Version': project.version,
            'Implementation-Vendor': 'AstroTweaks'
            //'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        )
    }

    // If have resources, make sure they are copied
    from sourceSets.main.output.classesDirs
    from sourceSets.main.output.resourcesDir
}



// ========== JSON MINIFIER ==========
afterEvaluate {
    processResources {
        doLast {
            def outputDir = destinationDir ?: outputs.files.singleFile
            fileTree(dir: outputDir, include: '**/*.json').each { file ->
                try {
                    file.text = groovy.json.JsonOutput.toJson(new groovy.json.JsonSlurper().parse(file))
                } catch (Exception ignore) {}
            }
        }
    }
}
