# The current version of Minecraft the project will use
mc_ver=1.12.2

# Mod Info
mod_name=AstroTweaks
mod_authors=["MrKoteo"]
mod_id=astrotweaks
mod_version=b6.1
group=astrotweaks
license=MIT
credits=
description=Some tweaks and additions for minecraft or your modpack.

# Manifold
manifold_version=2025.1.14

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true
#org.gradle.configuration-cache=true
org.gradle.java.installations.auto-download=false
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk8u392-b08-hotspot
